apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tenderduty.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "tenderduty.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "tenderduty.chart" . }}
data:
  config.yml: |-
{{ .Values.config | nindent 4 }}
