apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenderduty.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "tenderduty.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ include "tenderduty.chart" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tenderduty.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
{{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
